### ISSUE TITLE
main.js:2991 Uncaught (in promise) TypeError: this.attributeParsers[attribute] is not a function

### ISSUE THREAD

**Issue by leninanduin** [samuelsimoes/chrome-basecamp-notifier#24]
main.js:25033 Warning: bind(): You are binding a component method to the component. React does this for you automatically in a high-performance way, so you can safely remove this call. See undefined

main.js:25033 Warning: bind(): React component methods may only be bound to the component instance. See undefined

main.js:2991 Uncaught (in promise) TypeError: this.attributeParsers[attribute] is not a function
    at child.setAttribute (chrome-extension://fihjmkangcncdhnbnenfipalmcegljii/js/main.js:2991:47)
    at child.set (chrome-extension://fihjmkangcncdhnbnenfipalmcegljii/js/main.js:3005:12)
    at child._constructor (chrome-extension://fihjmkangcncdhnbnenfipalmcegljii/js/main.js:3020:10)
    at child.Fluxo.Base (chrome-extension://fihjmkangcncdhnbnenfipalmcegljii/js/main.js:2932:21)
    at new child (chrome-extension://fihjmkangcncdhnbnenfipalmcegljii/js/main.js:2878:39)
    at child.addFromData (chrome-extension://fihjmkangcncdhnbnenfipalmcegljii/js/main.js:3132:17)
    at child.addBunchFromData (chrome-extension://fihjmkangcncdhnbnenfipalmcegljii/js/main.js:3075:12)
    at child.resetFromData (chrome-extension://fihjmkangcncdhnbnenfipalmcegljii/js/main.js:3086:10)
    at Object._load (chrome-extension://fihjmkangcncdhnbnenfipalmcegljii/js/main.js:145:32)
    at Object.initialize (chrome-extension://fihjmkangcncdhnbnenfipalmcegljii/js/main.js:131:10)

Got this on the options page after granting permissions, I can't choose the proyect, 
ubuntu 14, Version 54.0.2840.100 (64-bit)

**Comment by socki03** [comment]
Bump.  Attempted to rebuild the plugin myself, but it appears to be built on a Unix platform, and I'm not great with ReactJS.

**Comment by amlcreative** [comment]
Bump. It's preventing me from using the Chrome extension at all.
